Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-098dd3a86ea110896
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, from, cloudformation]]
